In [138]:
import os
import numpy as np
import pandas as pd
import glob

import random
import base64

from io import BytesIO
from IPython.display import HTML

In [139]:
root_path = os.getcwd()
root_path

'D:\\database\\flickr30k_images'

In [4]:
from collections import defaultdict
# allPhotos = defaultdict(list)
allPhotos = []
for family in glob.glob(root_path + "/flickr30k_images/*"):
#     for mem in glob.glob(family+'/*'):
#         for photo in glob.glob(mem+'/*'):
    allPhotos.append(family)


In [5]:
import numpy as np
import cv2
len(allPhotos)

31782

In [6]:
data = pd.read_csv('results.csv', error_bad_lines=False)

b'Skipping line 3: expected 1 fields, saw 2\nSkipping line 22: expected 1 fields, saw 4\nSkipping line 39: expected 1 fields, saw 2\nSkipping line 48: expected 1 fields, saw 2\nSkipping line 68: expected 1 fields, saw 2\nSkipping line 92: expected 1 fields, saw 4\nSkipping line 93: expected 1 fields, saw 3\nSkipping line 94: expected 1 fields, saw 2\nSkipping line 97: expected 1 fields, saw 3\nSkipping line 99: expected 1 fields, saw 2\nSkipping line 101: expected 1 fields, saw 2\nSkipping line 117: expected 1 fields, saw 2\nSkipping line 133: expected 1 fields, saw 2\nSkipping line 187: expected 1 fields, saw 3\nSkipping line 202: expected 1 fields, saw 3\nSkipping line 208: expected 1 fields, saw 2\nSkipping line 222: expected 1 fields, saw 2\nSkipping line 238: expected 1 fields, saw 2\nSkipping line 241: expected 1 fields, saw 2\nSkipping line 247: expected 1 fields, saw 3\nSkipping line 252: expected 1 fields, saw 2\nSkipping line 278: expected 1 fields, saw 3\nSkipping line 292: 

In [7]:
data_np=pd.DataFrame.to_numpy(data)

In [8]:
data_list=[]
for i in range(len(data_np)):
    data_list.append(data_np[i][0])
add_vals=[]
for i in range(len(data_list)):
    count=0
    t=0
    for char in data_list[i]:
        if char!='|' and t==0:
            count=count+1
        else:
            t=1
    add_vals.append(count)
add_vals                

[14,
 14,
 14,
 14,
 12,
 12,
 12,
 12,
 12,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 12,
 12,
 12,
 12,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 12,
 12,
 12,
 12,
 12,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 12,
 12,
 12,
 12,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 13,


In [9]:
all_add_temp=[]

captions=[]
for i in range(len(data_list)):
#     print(data_list[i][0:add_vals[i]])
    all_add_temp.append(data_list[i][0:add_vals[i]])
for j in range(len(data_list)):
    captions.append(data_list[j][add_vals[j]+5:])
captions
len(captions)

141851

In [10]:
from collections import Counter
counter=Counter(all_add_temp)

all_add=[]
all_add=counter.keys()

num_occ=[]
for i in all_add:
    num_occ.append(counter[i])
len(num_occ)

31780

In [11]:
count=0;
img_sel=list()
cap_sel=list()
for num in num_occ:
    img_sel.append(all_add_temp[count])
    cap_sel.append(captions[count])
    count=count+num
# print(cap_sel)
# print(img_sel)
        
        
        
x_caps=cap_sel[0:500]
x_imgs=img_sel[0:500]

In [12]:
import string
table = str.maketrans('', '', string.punctuation)
pro_captions=[]
for desc_list in x_caps:
        desc = desc_list
        # tokenize
        desc = desc.split()
        # convert to lower case
        desc = [word.lower() for word in desc]
        # remove punctuation from each token
        desc = [w.translate(table) for w in desc]
        # remove hanging 's' and 'a'
        desc = [word for word in desc if len(word)>1]
        # remove tokens with numbers in them
        desc = [word for word in desc if word.isalpha()]
        # store as string
        desc_list = 'startseq ' + ' '.join(desc) + ' endseq'
        pro_captions.append(desc_list)
pro_captions

['startseq two young guys with shaggy hair look at their hands while hanging out in the yard endseq',
 'startseq several men in hard hats are operating giant pulley system endseq',
 'startseq child in pink dress is climbing up set of stairs in an entry way endseq',
 'startseq someone in blue shirt and hat is standing on stair and leaning against window endseq',
 'startseq two guy cooking and joking around with the camera endseq',
 'startseq two people in the photo are playing the guitar and the other is poking at him endseq',
 'startseq man sits in chair while holding large stuffed animal of lion endseq',
 'startseq girl is on rollerskates talking on her cellphone standing in parking lot endseq',
 'startseq an asian man wearing black suit stands near darkhaired woman and brownhaired woman endseq',
 'startseq two men in germany jumping over rail at the same time without shirts endseq',
 'startseq five ballet dancers caught mid jump in dancing studio with sunlight coming through window e

In [13]:
table = str.maketrans('', '', string.punctuation)
cap=[]
for desc_list in captions:
        desc = desc_list
        # tokenize
        desc = desc.split()
        # convert to lower case
        desc = [word.lower() for word in desc]
        # remove punctuation from each token
        desc = [w.translate(table) for w in desc]
        # remove hanging 's' and 'a'
        desc = [word for word in desc if len(word)>1]
        # remove tokens with numbers in them
        desc = [word for word in desc if word.isalpha()]
        # store as string
        desc_list = 'startseq ' + ' '.join(desc) + ' endseq'
        cap.append(desc_list)
word_count_threshold = 0
word_counts = {}
nsents = 0
for sent in cap:
    nsents += 1
    for w in sent.split(' '):
        word_counts[w] = word_counts.get(w, 0) + 1

vocab = [w for w in word_counts if word_counts[w] >= word_count_threshold]

print('preprocessed words %d ' % len(vocab))

preprocessed words 18155 


In [14]:
pics_path=[]
for pics in x_imgs:
    pics_path.append(root_path+"\\flickr30k_images\\"+ pics)
pics_path

['D:\\database\\flickr30k_images\\flickr30k_images\\1000092795.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\10002456.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1000268201.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1000344755.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1000366164.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1000523639.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1000919630.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\10010052.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001465944.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001545525.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001573224.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001633352.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001773457.jpg',
 'D:\\database\\flickr30k_images\\flickr30k_images\\1001896054.jpg',
 'D:\\database\\flickr30k_images\\flic

In [15]:
import cv2 as cv
pic_list=[]
# def img_to_array():
for pic in pics_path:
    print(pic)
    pic_list.append(cv.imread(pic,1))
pic_list_re=[]
for i in range(len(pic_list)-1):
    print(i)
    pic_list_re.append(cv.resize(pic_list[i],(299,299)))

D:\database\flickr30k_images\flickr30k_images\1000092795.jpg
D:\database\flickr30k_images\flickr30k_images\10002456.jpg
D:\database\flickr30k_images\flickr30k_images\1000268201.jpg
D:\database\flickr30k_images\flickr30k_images\1000344755.jpg
D:\database\flickr30k_images\flickr30k_images\1000366164.jpg
D:\database\flickr30k_images\flickr30k_images\1000523639.jpg
D:\database\flickr30k_images\flickr30k_images\1000919630.jpg
D:\database\flickr30k_images\flickr30k_images\10010052.jpg
D:\database\flickr30k_images\flickr30k_images\1001465944.jpg
D:\database\flickr30k_images\flickr30k_images\1001545525.jpg
D:\database\flickr30k_images\flickr30k_images\1001573224.jpg
D:\database\flickr30k_images\flickr30k_images\1001633352.jpg
D:\database\flickr30k_images\flickr30k_images\1001773457.jpg
D:\database\flickr30k_images\flickr30k_images\1001896054.jpg
D:\database\flickr30k_images\flickr30k_images\100197432.jpg
D:\database\flickr30k_images\flickr30k_images\100207720.jpg
D:\database\flickr30k_images\f

D:\database\flickr30k_images\flickr30k_images\1045124251.jpg
D:\database\flickr30k_images\flickr30k_images\1045309098.jpg
D:\database\flickr30k_images\flickr30k_images\1045521051.jpg
D:\database\flickr30k_images\flickr30k_images\10459869.jpg
D:\database\flickr30k_images\flickr30k_images\104669470.jpg
D:\database\flickr30k_images\flickr30k_images\104700891.jpg
D:\database\flickr30k_images\flickr30k_images\104763189.jpg
D:\database\flickr30k_images\flickr30k_images\1047921035.jpg
D:\database\flickr30k_images\flickr30k_images\104816788.jpg
D:\database\flickr30k_images\flickr30k_images\104824673.jpg
D:\database\flickr30k_images\flickr30k_images\104835889.jpg
D:\database\flickr30k_images\flickr30k_images\1048710776.jpg
D:\database\flickr30k_images\flickr30k_images\1049955899.jpg
D:\database\flickr30k_images\flickr30k_images\105077209.jpg
D:\database\flickr30k_images\flickr30k_images\1051205546.jpg
D:\database\flickr30k_images\flickr30k_images\1051290485.jpg
D:\database\flickr30k_images\flic

D:\database\flickr30k_images\flickr30k_images\109544260.jpg
D:\database\flickr30k_images\flickr30k_images\1095476286.jpg
D:\database\flickr30k_images\flickr30k_images\1095580424.jpg
D:\database\flickr30k_images\flickr30k_images\1095590286.jpg
D:\database\flickr30k_images\flickr30k_images\10956999.jpg
D:\database\flickr30k_images\flickr30k_images\10957138.jpg
D:\database\flickr30k_images\flickr30k_images\1095980313.jpg
D:\database\flickr30k_images\flickr30k_images\109608573.jpg
D:\database\flickr30k_images\flickr30k_images\1096097967.jpg
D:\database\flickr30k_images\flickr30k_images\1096165011.jpg
D:\database\flickr30k_images\flickr30k_images\1096305461.jpg
D:\database\flickr30k_images\flickr30k_images\1096395242.jpg
D:\database\flickr30k_images\flickr30k_images\109656696.jpg
D:\database\flickr30k_images\flickr30k_images\109671650.jpg
D:\database\flickr30k_images\flickr30k_images\1096800382.jpg
D:\database\flickr30k_images\flickr30k_images\109738763.jpg
D:\database\flickr30k_images\flic

D:\database\flickr30k_images\flickr30k_images\1131889107.jpg
D:\database\flickr30k_images\flickr30k_images\1131932671.jpg
D:\database\flickr30k_images\flickr30k_images\1132772170.jpg
D:\database\flickr30k_images\flickr30k_images\113291048.jpg
D:\database\flickr30k_images\flickr30k_images\11337976.jpg
D:\database\flickr30k_images\flickr30k_images\11338041.jpg
D:\database\flickr30k_images\flickr30k_images\113637264.jpg
D:\database\flickr30k_images\flickr30k_images\1136497229.jpg
D:\database\flickr30k_images\flickr30k_images\1136758631.jpg
D:\database\flickr30k_images\flickr30k_images\113678030.jpg
D:\database\flickr30k_images\flickr30k_images\113737410.jpg
D:\database\flickr30k_images\flickr30k_images\11382381.jpg
D:\database\flickr30k_images\flickr30k_images\1138784872.jpg
D:\database\flickr30k_images\flickr30k_images\1139029795.jpg
D:\database\flickr30k_images\flickr30k_images\11391827.jpg
D:\database\flickr30k_images\flickr30k_images\114051287.jpg
D:\database\flickr30k_images\flickr30

In [16]:
from keras.applications.inception_v3 import InceptionV3
from keras.models import Model
# Get the InceptionV3 model trained on imagenet data
model = InceptionV3(weights='imagenet')
# Remove the last layer (output softmax layer) from the inception v3
model_new = Model(model.input, model.layers[-2].output)

Using TensorFlow backend.
W1010 21:38:47.776548 11632 deprecation_wrapper.py:119] From d:\anacoda\envs\machine\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1010 21:38:48.073232 11632 deprecation_wrapper.py:119] From d:\anacoda\envs\machine\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1010 21:38:48.154483 11632 deprecation_wrapper.py:119] From d:\anacoda\envs\machine\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1010 21:38:48.274870 11632 deprecation_wrapper.py:119] From d:\anacoda\envs\machine\lib\site-packages\keras\backend\tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W1010 21:38:48.275962 11632 deprec

96116736/96112376 [==============================] - 440s 5us/step


In [91]:
pic_list_np=np.array(pic_list_re)
# print(pic_list_np.shape)
from keras.applications.inception_v3 import preprocess_input, decode_predictions
x = np.expand_dims(pic_list_np, axis=0)
print(x)
# preprocess images using preprocess_input() from inception module
x = preprocess_input(x)
x=x[0]


[[[[[  5   6   1]
    [  4   6   2]
    [  5   6   4]
    ...
    [239 235 204]
    [254 250 219]
    [252 250 220]]

   [[  3   3   3]
    [  4   4   4]
    [  5   5   5]
    ...
    [251 249 231]
    [251 254 233]
    [250 246 215]]

   [[  3   3   2]
    [  7   7   6]
    [  5   5   5]
    ...
    [ 84 135  79]
    [ 76 134  69]
    [210 238 184]]

   ...

   [[ 44  91  64]
    [ 88 156 125]
    [108 166 161]
    ...
    [131 185 161]
    [131 189 162]
    [131 197 162]]

   [[145 177 166]
    [125 182 171]
    [ 91 164 129]
    ...
    [ 93 162 112]
    [108 170 129]
    [ 74 163 109]]

   [[111 179 164]
    [150 198 170]
    [135 198 162]
    ...
    [129 187 158]
    [140 194 175]
    [ 86 152 126]]]


  [[[139 147 138]
    [149 159 148]
    [153 161 152]
    ...
    [210 212 212]
    [213 215 215]
    [207 209 209]]

   [[161 168 160]
    [171 180 171]
    [176 184 176]
    ...
    [209 211 211]
    [210 212 212]
    [209 211 211]]

   [[161 167 162]
    [175 182 176]
    [180 1

In [95]:
img_inc=model_new.predict(x)


In [116]:
import pickle
filename = 'image_inception_vecs.sav'
pickle.dump(model, open(filename, 'wb'))

In [140]:
filename = 'image_inception_vecs.sav'
img_inc = pickle.load(open(filename, 'rb'))


In [19]:
ixtoword = {}
wordtoix = {}
ix = 1
for w in vocab:
    wordtoix[w] = ix
    ixtoword[ix] = w
    ix += 1

In [25]:
len(wordtoix)

18155

In [26]:
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.corpus import stopwords
from string import punctuation
import re
def preProcessData(dataa):
    stopwords_en = list(set(stopwords.words('english')))
    def split(word): 
        return [char for char in word]   
    punchList = split(punctuation)

    print(stopwords_en)
    print('Punctuation :', punchList)

    wordTokenList = [word_tokenize(sent) for sent in dataa]
    lowercasingList = [[word.lower() for word in sentence] for sentence in wordTokenList]
#     noStopWordList = [[word for word in sentence if word not in stopwords_en] for sentence in lowercasingList]
    noPunchList = [[re.sub(r'([^\s\w]|_)+', '', word) for word in sentence] for sentence in lowercasingList]
    #noPunchList = [[word for word in sentence if word not in punchList] for sentence in noStopWordList]
    PP_data = [[word for word in sentence if word] for sentence in noPunchList]
    return PP_data
pp_data=preProcessData(pro_captions)
# for img,list_cap in img_picnum.items():
#     temp1in=[]
#     temp1out=[]
#     for seq in list_cap:
#         temp2in=[]
#         temp2out=[]
#         for i in range(1, len(seq)):
#                     # split into input and output pair
#             in_seq, out_seq = seq[:i], seq[i]
#                     # pad input sequence
#             in_seq = pad_sequences([in_seq], maxlen=max_length)[0]
#             # encode output sequence
#             out_seq = to_categorical([out_seq], num_classes=vocab_size)[0]
#             # store
#     #                     X1.append(photo)
#             temp2in.append(in_seq)
#             temp2out.append(out_seq)
#         temp1in.append(temp2in)
#         temp1out.append(temp2out)
#     img_inseq[img]=temp1in
#     img_outseq[img]=temp1out

['while', 'our', 'and', 'herself', 'below', 'just', 'most', 'with', "aren't", 'theirs', 'd', "needn't", "should've", "weren't", "shan't", "you've", 'until', 'whom', 'a', 'as', 'didn', 'don', 'mustn', 'here', 'to', "that'll", 'such', 'what', 'but', 'haven', 'during', 'me', 'these', 'more', 'because', "mustn't", 'ours', 'further', 'himself', 'has', 'my', 'ma', 'had', 'between', 'up', 'isn', 'an', 'over', 'needn', 'those', "shouldn't", 'does', 'ourselves', 'both', 'after', "don't", 'out', "didn't", 'now', 'mightn', 'are', "you'd", 'at', "doesn't", "wasn't", 'in', 'did', 'was', 'when', 'of', 'have', 'same', 'can', 'any', 'it', 'by', 'o', 'she', 've', 'this', 'wasn', 'there', 'then', 'they', 'will', 'than', 'be', 'itself', 'is', "it's", 'which', 'doesn', 'having', 'so', 'you', 'hasn', 'am', 'own', "isn't", 'he', "hadn't", 'been', 'from', 'some', 'yours', 'shan', 'ain', "won't", "you're", 'themselves', 'couldn', 'on', 'all', 'very', 'who', 'where', 'y', 'about', 'shouldn', 'through', 'above'

In [27]:
num_cap=[]
for sent in pp_data:
    temp=[]
    for word in sent:
        temp.append(wordtoix[word])
    num_cap.append(temp)
len(num_cap)
vocab_size=len(vocab)

In [28]:
temp1in=[]
temp1out=[]
for sent in num_cap:
    temp2in=[]
    temp2out=[]
    for i in range(1, len(sent)):
                    # split into input and output pair
        in_seq, out_seq = sent[:i], sent[i]
                # pad input sequence
        in_seq = pad_sequences([in_seq], maxlen=70)[0]
        # encode output sequence
        out_seq = to_categorical([out_seq], num_classes=vocab_size)[0]
        # store
#                     X1.append(photo)
        temp2in.append(in_seq)
        temp2out.append(out_seq)
    temp1in.append(temp2in)
    temp1out.append(temp2out)
    

In [42]:
# Load Glove vectors
glove_dir = 'glove'
embeddings_index = {} # empty dictionary
f = open(os.path.join(glove_dir, 'glove.6B.200d.txt'), encoding="utf-8")
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

In [44]:
embedding_dim = 200
# Get 200-dim dense vector for each of the 10000 words in out vocabulary
embedding_matrix = np.zeros((vocab_size+1, embedding_dim))
for word, i in wordtoix.items():
    #if i < max_words:
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in the embedding index will be all zeros
        embedding_matrix[i] = embedding_vector

In [108]:
inp_cap=[]
inp_img=[]
out=[]
for i in range(len(temp1in)-1):
    for j in range(len(temp1in[i])):
        inp_img.append(img_inc[i])
        inp_cap.append(temp1in[i][j])
        out.append(temp1out[i][j])
        

In [104]:
import keras
from keras.layers import Dense, Dropout, Flatten,Embedding
from keras.layers import Conv2D, MaxPooling2D

from keras.layers import Dense, Conv2D
from keras.layers import Flatten
from keras.layers import MaxPooling2D, GlobalAveragePooling2D
from keras.layers import Activation
from keras.layers import BatchNormalization
from keras.layers import Dropout,RNN,LSTM
from keras.models import Sequential
from keras.layers import Input, Dense, Flatten, GlobalMaxPool2D, GlobalAvgPool2D, Concatenate, Multiply, Dropout, Subtract, Add, Conv2D,add
from keras.models import Model
from keras import backend as K
from keras.preprocessing.image import load_img
from keras.optimizers import Adam


from keras import optimizers
def baseline():
    inputs1 = Input(shape=(2048,))
#     inner = Conv2D(100 , [3,3] )(inputs1)
#     inner = Flatten()(inputs1)
    fe1 = Dropout(0.5)(inputs1)
    fe2 = Dense(256, activation='relu')(fe1)

    # partial caption sequence model
    inputs2 = Input(shape=(max_length,))
    se1 = Embedding(vocab_size, embedding_dim, mask_zero=True)(inputs2)
    se2 = Dropout(0.5)(se1)
    se3 = LSTM(256)(se2)
    # decoder (feed forward) model
    merged = add([fe2, se3])
    decoder2 = Dense(256, activation='relu')(merged)
    decoder3 = Dense(512, activation='relu')(decoder2)
    decoder4 = Dense(1024, activation='relu')(decoder3)
    outputs = Dense(vocab_size, activation='softmax')(decoder4)

    # merge the two input models
    model = Model(inputs=[inputs1,inputs2], outputs=outputs)
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    model.summary()
    return model
model=baseline()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_20 (InputLayer)           (None, 70)           0                                            
__________________________________________________________________________________________________
input_19 (InputLayer)           (None, 2048)         0                                            
__________________________________________________________________________________________________
embedding_7 (Embedding)         (None, 70, 200)      3631000     input_20[0][0]                   
__________________________________________________________________________________________________
dropout_17 (Dropout)            (None, 2048)         0           input_19[0][0]                   
__________________________________________________________________________________________________
dropout_18

In [109]:
ninp_cap=np.array(inp_cap)
ninp_img=np.array(inp_img)
nout=np.array(out)

In [ ]:
model.fit([ninp_img,ninp_cap],nout ,epochs=50,verbose=1,batch_size=300)

Epoch 1/50
7574/7574 [==============================] - 142s 19ms/step - loss: 0.9094 - acc: 0.7099
Epoch 2/50
7574/7574 [==============================] - 141s 19ms/step - loss: 0.8513 - acc: 0.7237
Epoch 3/50
7574/7574 [==============================] - 150s 20ms/step - loss: 0.7902 - acc: 0.7439
Epoch 4/50
6600/7574 [=========================>....] - ETA: 18s - loss: 0.7278 - acc: 0.7632

In [119]:
max_length=70
def greedySearch(photo):
    in_text = 'startseq'
    for i in range(max_length):
        sequence = [wordtoix[w] for w in in_text.split() if w in wordtoix]
        sequence = pad_sequences([sequence], maxlen=max_length)
#         print(sequence)
        yhat = model.predict([photo,sequence], verbose=0)
#         print(yhat.shape)
        yhat = np.argmax(yhat)
#         print(yhat)
        word = ixtoword[yhat]
        in_text += ' ' + word
        if word == 'endseq':
            break
    final = in_text.split()
    final = final[1:-1]
    final = ' '.join(final)
    return final

In [65]:
allPhotos

['D:\\database\\flickr30k_images/flickr30k_images\\1000092795.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\10002456.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1000268201.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1000344755.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1000366164.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1000523639.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1000919630.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\10010052.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001465944.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001545525.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001573224.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001633352.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001773457.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1001896054.jpg',
 'D:\\database\\flickr30k_images/flickr30k_images\\1

In [144]:
pic_p=root_path+"\\flickr30k_images\\"+ img_sel[591]
print(pic_p)
pic_l=cv.imread(pic_p,1)
pic_lr=cv.resize(pic_l,(299,299))

D:\database\flickr30k_images\flickr30k_images\1191939974.jpg


In [145]:
pic_lrn=np.array(pic_lr)
j = np.expand_dims(pic_lrn,axis=0)
# preprocess images using preprocess_input() from inception module
j = preprocess_input(j)
j=model_new.predict(j)

In [146]:
greedySearch(j)

'man in red shirt and hat is standing on the porch while large family'

In [72]:
dinp_cap=pd.DataFrame(ninp_cap)
dinp_cap


0   1   2   3   4   5   6   7   8   9   ...    60    61    62    63  \
0      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
1      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
2      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
3      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
4      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
5      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
6      0   0   0   0   0   0   0   0   0   0  ...     0     0     0     1   
7      0   0   0   0   0   0   0   0   0   0  ...     0     0     1     2   
8      0   0   0   0   0   0   0   0   0   0  ...     0     1     2     3   
9      0   0   0   0   0   0   0   0   0   0  ...     1     2     3     4   
10     0   0   0   0   0   0   0   0   0   0  ...     2     3     4     5   
11     0   0   0   0   0   0   0   0   0   0  ...     3     4     5     6   
12     0   0   0   0   0   0   0   0   0   0  ...     4     5     6     7   
13     0   0   0   0   0   0   0   0   0   0  ...     5     6     7     8   
14     0   0   0   0   0   0   0   0   0   0  ...     6     7     8     9   
15     0   0   0   0   0   0   0   0   0   0  ...     7     8     9    10   
16     0   0   0   0   0   0   0   0   0   0  ...     8     9    10    11   
17     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
18     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
19     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
20     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
21     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
22     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
23     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     1   
24     0   0   0   0   0   0   0   0   0   0  ...     0     0     1    33   
25     0   0   0   0   0   0   0   0   0   0  ...     0     1    33    19   
26     0   0   0   0   0   0   0   0   0   0  ...     1    33    19    15   
27     0   0   0   0   0   0   0   0   0   0  ...    33    19    15    34   
28     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
29     0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   ...   
7544   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7545   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     1   
7546   0   0   0   0   0   0   0   0   0   0  ...     0     0     1    24   
7547   0   0   0   0   0   0   0   0   0   0  ...     0     1    24    15   
7548   0   0   0   0   0   0   0   0   0   0  ...     1    24    15   433   
7549   0   0   0   0   0   0   0   0   0   0  ...    24    15   433   434   
7550   0   0   0   0   0   0   0   0   0   0  ...    15   433   434    88   
7551   0   0   0   0   0   0   0   0   0   0  ...   433   434    88    14   
7552   0   0   0   0   0   0   0   0   0   0  ...   434    88    14    25   
7553   0   0   0   0   0   0   0   0   0   0  ...    88    14    25   815   
7554   0   0   0   0   0   0   0   0   0   0  ...    14    25   815  2545   
7555   0   0   0   0   0   0   0   0   0   0  ...    25   815  2545   149   
7556   0   0   0   0   0   0   0   0   0   0  ...   815  2545   149   823   
7557   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7558   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7559   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7560   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7561   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7562   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0   
7563   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     1   
75

In [67]:
tout=nout.T

In [69]:
tout.shape

(18155, 7574)